//
//  DeepLinkRouterTests.swift
//  DeepLinkMacros
//
//  Created by @iamjason on 7/6/25.
//  Copyright (c) 2025. All rights reserved.
//  Licensed under the MIT License.
//

import XCTest
@testable import DeepLinkRouting

// MARK: - Test Destination (Bob's Burgers themed)

enum BobsBurgersDestination: Equatable, DeepLinkRoutable {
  case restaurant
  case employee(employeeId: Int)
  case burgerOfTheDay(slug: String, showRecipe: Bool?)
  case menuSearch(query: String?, page: Int?)
  case episode(slug: String)
  case kitchen

  // Manual route definitions for testing (normally generated by macro)
  static var allRoutes: [DeepLinkRouteDefinition<BobsBurgersDestination>] {
    [
      DeepLinkRouteDefinition(
        pattern: "/",
        segments: [],
        queryParams: [],
        build: { _ in .restaurant }
      ),
      DeepLinkRouteDefinition(
        pattern: "/employees/:id",
        segments: [.literal("employees"), .parameter("id")],
        queryParams: [],
        build: { params in
          guard let employeeId = params.pathInt("id") else { return nil }
          return .employee(employeeId: employeeId)
        }
      ),
      DeepLinkRouteDefinition(
        pattern: "/burgers/:slug",
        segments: [.literal("burgers"), .parameter("slug")],
        queryParams: ["showRecipe"],
        build: { params in
          guard let slug = params.path("slug") else { return nil }
          let showRecipe = params.queryBool("showRecipe")
          return .burgerOfTheDay(slug: slug, showRecipe: showRecipe)
        }
      ),
      DeepLinkRouteDefinition(
        pattern: "/menu",
        segments: [.literal("menu")],
        queryParams: ["q", "page"],
        build: { params in
          let query = params.query("q")
          let page = params.queryInt("page")
          return .menuSearch(query: query, page: page)
        }
      ),
      DeepLinkRouteDefinition(
        pattern: "/episodes/**/:slug",
        segments: [.literal("episodes"), .wildcard, .parameter("slug")],
        queryParams: [],
        build: { params in
          guard let slug = params.path("slug") else { return nil }
          return .episode(slug: slug)
        }
      ),
    ]
  }
}

// MARK: - Router Tests

final class DeepLinkRouterTests: XCTestCase {

  var router: DeepLinkRouter<BobsBurgersDestination>!

  override func setUp() {
    super.setUp()
    router = DeepLinkRouter()
  }

  // MARK: - Basic Matching

  func testMatchRestaurant() {
    let result = router.match("/")
    XCTAssertEqual(result, .restaurant)
  }

  func testMatchEmployee() {
    // Bob is employee #1
    let result = router.match("/employees/1")
    XCTAssertEqual(result, .employee(employeeId: 1))
  }

  func testMatchEmployeeWithDifferentId() {
    // Tina is employee #2
    let result = router.match("/employees/2")
    XCTAssertEqual(result, .employee(employeeId: 2))
  }

  func testMatchBurgerOfTheDay() {
    let result = router.match("/burgers/bet-it-all-on-black-garlic-burger")
    XCTAssertEqual(result, .burgerOfTheDay(slug: "bet-it-all-on-black-garlic-burger", showRecipe: nil))
  }

  func testMatchBurgerOfTheDayWithRecipe() {
    let result = router.match("/burgers/new-bacon-ings-burger?showRecipe=true")
    XCTAssertEqual(result, .burgerOfTheDay(slug: "new-bacon-ings-burger", showRecipe: true))
  }

  func testMatchMenuSearch() {
    let result = router.match("/menu")
    XCTAssertEqual(result, .menuSearch(query: nil, page: nil))
  }

  func testMatchMenuSearchWithQuery() {
    let result = router.match("/menu?q=fries&page=2")
    XCTAssertEqual(result, .menuSearch(query: "fries", page: 2))
  }

  func testMatchEpisodeWithWildcard() {
    let result = router.match("/episodes/season/3/sheesh-cab-bob")
    XCTAssertEqual(result, .episode(slug: "sheesh-cab-bob"))
  }

  // MARK: - No Match Cases

  func testNoMatchForUnknownPath() {
    let result = router.match("/jimmy-pestos")
    XCTAssertNil(result)
  }

  func testNoMatchForInvalidEmployeeId() {
    let result = router.match("/employees/teddy")
    XCTAssertNil(result) // Int conversion fails
  }

  func testNoMatchForKitchenRoute() {
    // Kitchen has no route in allRoutes (like settings)
    let result = router.match("/kitchen")
    XCTAssertNil(result)
  }

  // MARK: - Case Insensitivity

  func testCaseInsensitiveMatching() {
    let result = router.match("/EMPLOYEES/1")
    XCTAssertEqual(result, .employee(employeeId: 1))
  }

  // MARK: - URL Matching

  func testMatchWithFullURL() {
    let url = URL(string: "https://bobsburgers.com/employees/1")!
    let result = router.match(url)
    XCTAssertEqual(result, .employee(employeeId: 1))
  }

  func testMatchWithQueryString() {
    let url = URL(string: "https://bobsburgers.com/menu?q=burger&page=1")!
    let result = router.match(url)
    XCTAssertEqual(result, .menuSearch(query: "burger", page: 1))
  }

  // MARK: - Detailed Matching

  func testMatchWithDetails() {
    let result = router.matchWithDetails("/employees/1")

    XCTAssertNotNil(result)
    XCTAssertEqual(result?.destination, .employee(employeeId: 1))
    XCTAssertEqual(result?.pattern, "/employees/:id")
    XCTAssertEqual(result?.parameters.path("id"), "1")
  }

  // MARK: - Route Discovery

  func testAllRoutesDiscovered() {
    // Should have 5 routes (restaurant, employee, burgerOfTheDay, menuSearch, episode)
    // kitchen is not included because it has no route
    XCTAssertEqual(router.routes.count, 5)
  }
}
