//
//  DeepLinkRouteDefinition.swift
//  DeepLinkMacros
//
//  Created by @iamjason on 7/6/25.
//  Copyright (c) 2025. All rights reserved.
//  Licensed under the MIT License.
//

import Foundation

/// A route definition generated by @DeepLinkRoute macro.
public struct DeepLinkRouteDefinition<Destination>: Sendable {

  /// The original URL pattern (e.g., "/users/:id")
  public let pattern: String

  /// Parsed pattern segments for matching
  public let segments: [PatternSegment]

  /// Query parameter names to extract
  public let queryParams: [String]

  /// Builds the destination from extracted parameters
  public let build: @Sendable (RouteParameters) -> Destination?

  public init(
    pattern: String,
    segments: [PatternSegment],
    queryParams: [String] = [],
    build: @escaping @Sendable (RouteParameters) -> Destination?
  ) {
    self.pattern = pattern
    self.segments = segments
    self.queryParams = queryParams
    self.build = build
  }
}
